name: Integration tests

on: [push]


jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      openssh-server:
        image: tiangolo/uwsgi-nginx-flask:python3.8-alpine
        ports:
          - 5000:5000
        volumes:
          - /home/runner/:/app/
        options: --entrypoint 'entry.sh'
        

    steps:
      - uses: actions/checkout@v3


      - name: Connect to http
        run: |
          pwd 
          curl -X GET 0.0.0.0:5000/image_creation/images/download/jja


